heaven/src/Heaven/Heaven/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Web.urls")),
    path('api/', include ("api.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

heaven/src/Heaven/Web/urls.py
from django.urls import path
from . import views

app_name = "Web"
urlpatterns = [
    path("", views.index, name="index"),
    path("signup", views.signup, name="signup"),
    path("signup_form", views.signup_form, name="signup_form"),
    path("login", views.login, name="login"),
    path('upload/', views.upload_video, name='upload_video'),
    path('upload_data/', views.upload, name='upload'),
    path('home', views.home, name='home'),
    path('id/<int:video_id>/', views.video_detail, name='video_detail'),
]

heaven/src/Heaven/templates/listing_page/home.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <title>Home</title>
    {% include 'includes/tabler.html' %} 
    <script src="{% static 'common/jquery-3.6.1.min.js' %}"></script>
    <script src="{% static 'home/home.js' %}"></script>
    {% comment %}
    
    {% endcomment %} {% comment %}
    <script src="{% static 'teachers/js/teacher_login.js' %}"></script>
    {% endcomment %}
  </head>
  <body>
    <div class="page-wrapper">
      <!-- Page header -->
      <div class="page-header d-print-none">
        <div class="container-xl">
          <div class="row g-2 align-items-center">
            <div class="col">
              <h2 class="page-title">Gallery</h2>
              <div class="text-secondary mt-1">1-12 of {{videos.length}} photos</div>
            </div>
            <!-- Page title actions -->
            <div class="col-auto ms-auto d-print-none">
              <div class="d-flex">
                <div class="me-3">
                  <div class="input-icon">
                    <input
                      type="text"
                      value=""
                      class="form-control"
                      placeholder="Search…"
                    />
                    <span class="input-icon-addon">
                      <!-- Download SVG icon from http://tabler-icons.io/i/search -->
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        class="icon"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        stroke-width="2"
                        stroke="currentColor"
                        fill="none"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      >
                        <path
                          stroke="none"
                          d="M0 0h24v24H0z"
                          fill="none"
                        ></path>
                        <path
                          d="M10 10m-7 0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0"
                        ></path>
                        <path d="M21 21l-6 -6"></path>
                      </svg>
                    </span>
                  </div>
                </div>
                <a class="btn btn-primary" id="create-btn">
                  <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="icon"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    stroke-width="2"
                    stroke="currentColor"
                    fill="none"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                    <path d="M12 5l0 14"></path>
                    <path d="M5 12l14 0"></path>
                  </svg>
                  Add New Videos
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Page body -->
      <div class="page-body">
        <div class="container-xl">
          <div class="row row-cards">
            {% for video in videos %}
            <div class="col-sm-6 col-lg-3" onclick="getId('{{ video.id }}')" >
              <div class="card card-sm">
                <a href="{% url 'Web:video_detail' video.id %}" class="d-block">
                  <img src="http://127.0.0.1:8000/media/{{ video.thumbnail }}" class="card-img-top"/>
              </a>
                <div class="card-body">
                  <div class="d-flex align-items-center">
                    
                    <div>
                      <div>{{video.title}}</div>
                      
                    </div>
                    
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}

          </div>
          <div class="d-flex">
            <ul class="pagination ms-auto">
              <li class="page-item disabled">
                <a
                  class="page-link"
                  href="#"
                  tabindex="-1"
                  aria-disabled="true"
                >
                  <!-- Download SVG icon from http://tabler-icons.io/i/chevron-left -->
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="icon"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    stroke-width="2"
                    stroke="currentColor"
                    fill="none"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                    <path d="M15 6l-6 6l6 6"></path>
                  </svg>
                  prev
                </a>
              </li>
              <li class="page-item"><a class="page-link" href="#">1</a></li>
              <li class="page-item active">
                <a class="page-link" href="#">2</a>
              </li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item"><a class="page-link" href="#">4</a></li>
              <li class="page-item"><a class="page-link" href="#">5</a></li>
              <li class="page-item">
                <a class="page-link" href="#">
                  next
                  <!-- Download SVG icon from http://tabler-icons.io/i/chevron-right -->
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="icon"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    stroke-width="2"
                    stroke="currentColor"
                    fill="none"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                    <path d="M9 6l6 6l-6 6"></path>
                  </svg>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <footer class="footer footer-transparent d-print-none">
        <div class="container-xl">
          <div class="row text-center align-items-center flex-row-reverse">
            <div class="col-lg-auto ms-lg-auto">
              <ul class="list-inline list-inline-dots mb-0">
                <li class="list-inline-item">
                  <a
                    href="https://tabler.io/docs"
                    target="_blank"
                    class="link-secondary"
                    rel="noopener"
                    >Documentation</a
                  >
                </li>
                <li class="list-inline-item">
                  <a href="./license.html" class="link-secondary">License</a>
                </li>
                <li class="list-inline-item">
                  <a
                    href="https://github.com/tabler/tabler"
                    target="_blank"
                    class="link-secondary"
                    rel="noopener"
                    >Source code</a
                  >
                </li>
                <li class="list-inline-item">
                  <a
                    href="https://github.com/sponsors/codecalm"
                    target="_blank"
                    class="link-secondary"
                    rel="noopener"
                  >
                    <!-- Download SVG icon from http://tabler-icons.io/i/heart -->
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      class="icon text-pink icon-filled icon-inline"
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      stroke-width="2"
                      stroke="currentColor"
                      fill="none"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    >
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <path
                        d="M19.5 12.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572"
                      ></path>
                    </svg>
                    Sponsor
                  </a>
                </li>
              </ul>
            </div>
            <div class="col-12 col-lg-auto mt-3 mt-lg-0">
              <ul class="list-inline list-inline-dots mb-0">
                <li class="list-inline-item">
                  Copyright © 2023
                  <a href="." class="link-secondary">Tabler</a>. All rights
                  reserved.
                </li>
                <li class="list-inline-item">
                  <a
                    href="./changelog.html"
                    class="link-secondary"
                    rel="noopener"
                  >
                    v1.0.0-beta20
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>

heaven/src/Heaven/templates/listing_page/view.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <title>Home</title>
    {% include 'includes/tabler.html' %}
    <script src="{% static 'common/jquery-3.6.1.min.js' %}"></script>
    <link href="https://vjs.zencdn.net/8.6.1/video-js.css" rel="stylesheet" />
    <script src="https://vjs.zencdn.net/8.6.1/video.min.js"></script>
    <script src="{% static 'home/view.js' %}"></script>

  </head>
  <body>
    <div class="container" id('{{video.id}}')>
      <div class="card m-3">
        <div class="card-body d-flex justify-content-center">
          <div>
            <video width="640" height="360" controls="controls" preload="auto">
              {% comment %} <source id="video-player" src="" type="video/mp4" /> {% endcomment %}
              <source src="{{ video.video_file.url }}" type="video/mp4" />
              Your browser does not support the video tag.
            </video>
          </div> 
          
          {% comment %} <div>
            <video id="video-player" data-video-id="{{ video.id }}"
              id="my-video"
              class="video-js"
              controls
              preload="true"
              width="640"
              height="264"
              poster="{{video.thumbnail}}"
              data-setup="{}"
            >
              <source src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" type="video/mp4" />
              <source src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" type="video/webm" />
              
              <p class="vjs-no-js">
                To view this video please enable JavaScript, and consider
                upgrading to a web browser that
                <a
                  href="https://videojs.com/html5-video-support/"
                  target="_blank"
                  >supports HTML5 video</a
                >
              </p>
            </video>
          </div> {% endcomment %}
          <div></div>
        </div>
      </div>
    </div>
    
  </body>
</html>