heaven/src/Heaven/Heaven/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Web.urls")),
    path('api/', include ("api.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

heaven/src/Heaven/Web/urls.py
from django.urls import path
from . import views

app_name = "Web"
urlpatterns = [
    path("", views.index, name="index"),
    path("signup", views.signup, name="signup"),
    path("signup_form", views.signup_form, name="signup_form"),
    path("login", views.login, name="login"),
    path('upload/', views.upload_video, name='upload_video'),
    path('upload_data/', views.upload, name='upload'),
    path('home', views.home, name='home'),
    path('id/<int:video_id>/', views.video_detail, name='video_detail'),
]

heaven/src/Heaven/templates/signup/signup.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>Signup</title>
        {% include 'includes/bootstrap.html' %}
        {% comment %} <script src="{% static 'common/jquery-3.6.1.min.js' %}"></script> {% endcomment %}
        {% comment %} <script src="{% static 'teachers/js/teacher_login.js' %}"></script> {% endcomment %}
    </head>
    <body>
        <h2 class="text-center">Signup</h2>
        <form method="post" action="{% url 'Web:signup_form' %}">
            {% csrf_token %}
            <p>
                <label for="">username</label>
                <input type="text" name="username">
            </p>
            <p>
                <label for="">Password</label>
                <input type="password" name="password">
            </p>
            <input type="submit" value="signup" class="btn">
            
        </form>
    </body>
</html>